#Plot 6
baltimore_road=subset(NEI,fips=="24510" & type=="ON-ROAD")
baltimore_road$year=as.factor(baltimore_road$year)
baltimore_road$type=as.factor(baltimore_road$type)
total2=aggregate(Emissions~year,baltimore_road,sum)
cali_road=subset(NEI,fips=="06037" & type=="ON-ROAD")
cali_road$year=as.factor(cali_road$year)
cali_road$type=as.factor(cali_road$type)
total3=aggregate(Emissions~year,cali_road,sum)
total2$city=paste(rep("Baltimore",4))
total3$city=paste(rep("California",4))
comb=as.data.frame(rbind(total2,total3))
png(filename="~/Documents/Exploratory Data Analysis/plot6.png")
ggplot(comb,aes(x=year,y=Emissions))+geom_bar(stat="identity",aes(fill=year))+facet_grid(.~city)+guides(fill=F)+ ggtitle("Comparison between LA and Baltimore for motor vehicle emissions")
dev.off()
